### ISSUE TITLE
Does animalCategoryStructural need a validFrom / To ?

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0266#10]
Do we need validFrom / To need a validFrom  and validTo (referencing eCH-0261:Validity)?

The argument for this is so the category can evolve. 

The primary argument against this is that this is not an issue for a data standard, but rather for an interface implementation.

Discuss with Dani M. @ BLW.

**Options:**
1. No validity.   The standard does not prescribe this and the implementation of validity is a matter of a hosting system. For an example, see BurWeb localUnit, legalUnit, etc.
2. Validity at the level of an AnimalCategoryStructural individual entry.  Example Hoduflu Products and MetaProducts. Each entry is individually fitted with a validity.
3. Validity at the level of an AnimalCategoryStructural "report" which aggregates or reports on the individual entries.  (Such a report is not -- as yet -- part of this standard, so this is more of a future option.) There are some examples of this at the BLW, the primary one being a new version of the Merkmalskatalog.  This is typically released at yearly intervals. Another example is the Hoduflu "Gehaltstabelle" which includes all MetaProducts. The Gehaltstablelle is typically released once or twice per year.  For an external example, see ISO 3166-3 (country codes) in which any change to any entry results in a new standard.  In other words, in that example, the list is versioned and no explicit indication of _what_ changed within that list is not easily derivable.

**The various stakeholders are:**

- Technical consumers (users of an interface built upon the standard). Such consumers prefer granular validity.

- Business report consumers (readers of a published report or list). Such consumers probably do not need the granularity.

 

**How did we do this elsewhere?**
In the Agrar data standards, we currently do not have a single unified approach. Of particular note, eCH-0265 _Flächen und Kulturen_ adopted option 2 across the board.

**Comment by AFoletti** [comment]
My own 2 cents on that, to be discussed this afternoon:

In my opinion, highly granular validity does not add complexity to the model (it is not a new class and simply adds a standard element to the animalCategoryStructural). It also adds relatively little effort to fill up.
On the other hand, it is my understanding that this is quite an important piece of information in some usecases.
And since the time dimension is quite a nasty one and everyone does it in his own way, I find it particularly useful to standardize it in order to obtain a much better and coherent understanding of the information available.

**Comment by montanajava** [comment]
Decision taken: Option # 2. New issue #36 created with the task to implement this in Vs. 2.
