### ISSUE TITLE
Simplify UML

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0266#14]
Create 3 diagrams:

1. Overview Simplify to include only the basics: no reference to external eCHs, no reporting elements/entities, no cardinalities.
2. AnimalCategoryStructural
3. Report UML with feedback from 3.15 - 3.25

**Comment by montanajava** [comment]
A proposal
[eCH_0266__1_0__Tiere.drawio.pdf](https://github.com/blw-ofag-ufag/eCH-0266/files/15184376/eCH_0266__1_0__Tiere.drawio.pdf)

**Comment by AFoletti** [comment]
> A proposal, attached:
> 
> [eCH_0266__1_0__Tiere.drawio.pdf](https://github.com/blw-ofag-ufag/eCH-0266/files/15184515/eCH_0266__1_0__Tiere.drawio.pdf)
> 
> @AFoletti @hurni @lars-steffen @RyanStuder-Work @anjaaeschlimann One thing becomes glaringly obvious: Both AnimalCategoryStructural and AnimalCategoryPRIF reference ZoologicalAnimal. The attributeName in AnimalCategoryStructural should probably contain the word "override"

I allow myself to disagree since how the standard is defined today, it's possible to have an AnimalCategoryStructural without any indication of AnimalCategoryPRIF (see animalGroupType) and the animalCategoryStructuralType can miss any reference to an animalCategoryPRIF (minOccurs="0").
As a consequence, it's possible to have a reference to zoologicalAnimal only via AnimalCategoryStructural, which would then override nothing at all.
Moreover, it is expected that the two references (if both exist) to zoologicalAnimal are concordant. If thus should not be the case, we have a deeper problem and no way to actually decide which one is the correct (overriding) one.

Makes sense?
